apiVersion: apps/v1
kind: Deployment
metadata:
  name: schema-registry
  labels:
    app: schema-registry
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: schema-registry
  template:
    metadata:
      labels:
        app: schema-registry
    spec:
      containers:
        - name: schema-registry
          image: {{ .Values.schemaRegistry.image }}
          ports:
            - containerPort: 8081
          env:
            - name: SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL
              value: "{{ .Values.schemaRegistry.config.kafkaStoreConnectionUrl }}"
            - name: SCHEMA_REGISTRY_HOST_NAME
              value: "{{ .Values.schemaRegistry.config.hostName }}"
            - name: SCHEMA_REGISTRY_LISTENERS
              value: "{{ .Values.schemaRegistry.config.listeners }}"