apiVersion: v1
kind: Service
metadata:
  name: schema-registry-service
  labels:
    app: schema-registry
spec:
  type: {{ .Values.schemaRegistry.service.type }}
  ports:
    - port: {{ .Values.schemaRegistry.service.port }}
      targetPort: 8081
      protocol: TCP
      name: http
      nodePort: {{ .Values.schemaRegistry.service.nodePort }}
  selector:
    app: schema-registry