apiVersion: v1
kind: Service
metadata:
  name: debezium-service
  labels:
    app: debezium
spec:
  type: {{ .Values.debezium.service.type }}
  ports:
    - port: {{ .Values.debezium.service.port }}
      targetPort: 8083
      protocol: TCP
      name: http
      nodePort: {{ .Values.debezium.service.nodePort }}
  selector:
    app: debezium