apiVersion: v1
kind: Service
metadata:
  name: zookeeper-service
  labels:
    app: zookeeper
spec:
  type: {{ .Values.zookeeper.service.type }}
  ports:
    - port: {{ .Values.zookeeper.service.port }}
      targetPort: 2181
      protocol: TCP
      name: client
      nodePort: {{ .Values.zookeeper.service.nodePort }}
  selector:
    app: zookeeper