apiVersion: v1
kind: Service
metadata:
  name: kafka-ui-service
  labels:
    app: kafka-ui
spec:
  type: {{ .Values.kafkaUI.service.type }}
  ports:
    - port: {{ .Values.kafkaUI.service.port }}
      targetPort: 8080
      protocol: TCP
      name: http
      nodePort: {{ .Values.kafkaUI.service.nodePort }}
  selector:
    app: kafka-ui